### ISSUE TITLE
UML for Interfaces

### ISSUE THREAD

**Issue by ClarkLindsay** [ClarkLindsay/trumpet#17]
![capture](https://cloud.githubusercontent.com/assets/25178240/24505475/9d22af46-151f-11e7-92a0-276f5a04f861.PNG)

@anthonykulis

**Comment by anthonykulis** [comment]
add 4 more (i think its a total of 6) in other classes. i think pressable better fits with keys

**Comment by ClarkLindsay** [comment]
Thanks

**Comment by ClarkLindsay** [comment]
![-blank uml - page 1](https://cloud.githubusercontent.com/assets/25178240/24507495/38553d20-1526-11e7-92a3-0f7e845ac037.jpeg)
@anthonykulis

**Comment by ClarkLindsay** [comment]
@anthonykulis 
BTW, I did the polymorphing in Driver class.

**Comment by anthonykulis** [comment]
+25, +5
