### ISSUE TITLE
Trumpet colors can be "null"

### ISSUE THREAD

**Issue by anthonykulis** [ClarkLindsay/trumpet#4]
https://github.com/ClarkLindsay/trumpet/blob/master/edu/jalc/trumpet/material/Material.java#L17

There is no reason I cannot have a metal finish in the "raw". I work heavily in metals as a hobby and have done it a million times. Forcing a color doesn't make sense.

**Comment by ClarkLindsay** [comment]
If I set color to final (issue 3) shouldn't the whole setter method be deleted?
